auth_app/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view

app_name = 'auth_app'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_view, 
    get_cart_view, 
    cart, 
    delete_cart_item_view, 
    checkout,
    )

app_name = 'cart'
urlpatterns = [
    path('cart/', cart, name='cart'),
    path('add_to_cart/', add_to_cart_view, name='add_to_cart'),
    path('get_cart/', get_cart_view, name='get_cart'),
    path('remove_cart/<int:product_id>/', delete_cart_item_view, name='delete_cart_item'),
    path('checkout/', checkout, name='checkout'),
]

templates/modals/login.html
{% load static %}
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="close-btn">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="identityBox">
                    <div class="form-wrapper">
                        <h1 id="loginModalLabel">welcome back!</h1>
                        <form id="loginForm" method="post" action="{% url 'auth_app:login' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            <input class="inputField" type="email" name="username" placeholder="Email Address">
                            <input class="inputField" type="password" name="password" placeholder="Enter Password">
                            <div class="input-check remember-me">
                                <div class="checkbox-wrapper">
                                    <input type="checkbox" class="form-check-input" name="save-for-next"
                                        id="saveForNext">
                                    <label for="saveForNext">Remember me</label>
                                </div>
                                <div class="text"> <a href="index-2.html">Forgot Your password?</a> </div>
                                
                            </div>
                            
                            <div class="loginBtn">
                                <input type="submit" value="Log in" class="theme-btn rounded-0">
                            </div>
                            <div class="text"> <a href="{% url 'auth_app:register' %}">Dont have an account? Register</a> </div>
                        </form>
                        <div class="orting-badge">
                            Or
                        </div>
                        <div>
                            <a class="another-option" href="https://www.google.com/">
                                <img src="{% static 'assets/img/google.png' %}" alt="google">
                                Continue With Google
                            </a>
                        </div>
                        <div>
                            <a class="another-option another-option-two" href="https://www.facebook.com/">
                                <img src="{% static 'assets/img/facebook.png' %}" alt="google">
                                Continue With Facebook
                            </a>
                        </div>
                    </div>

                    <div class="banner">
                        <button type="button" class="rounded-0 login-btn" data-bs-toggle="modal"
                            data-bs-target="#loginModal">Log in</button>
                        <button type="button" class="theme-btn rounded-0 register-btn" data-bs-toggle="modal"
                            data-bs-target="#registrationModal">Create
                            Account</button>
                        <div class="loginBg">
                            <img src="assets/img/signUpbg.jpg" alt="signUpBg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/modals/register.html
{% load static %}
<div class="modal fade" id="registrationModal" tabindex="-1" aria-labelledby="registrationModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="close-btn">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="identityBox">
                    <div class="form-wrapper">
                        <h1 id="registrationModalLabel">Create account!</h1>
                        <form id="loginForm" method="post" action="{% url 'auth_app:register' %}">
                            {% csrf_token %}
                            <input class="inputField" type="text" name="first_name" id="first_name" placeholder="First Name">
                            <input class="inputField" type="text" name="last_name" id="last_name" placeholder="Last Name">
                            <input class="inputField" type="text" name="username" id="username" placeholder="User Name">
                            <input class="inputField" type="email" name="email" placeholder="Email Address">
                            <input class="inputField" type="password" name="password" placeholder="Enter Password">
                            <input class="inputField" type="password" name="confirm_password"
                                placeholder="Enter Confirm Password">
                            <div class="input-check remember-me">
                                <div class="checkbox-wrapper">
                                    <input type="checkbox" class="form-check-input" name="save-for-next"
                                        id="rememberMe">
                                    <label for="rememberMe">Remember me</label>
                                </div>
                                <div class="text"> <a href="index-2.html">Forgot Your password?</a> </div>
                            </div>
                            <div class="loginBtn">
                                <input type="submit" value="Register" class="theme-btn rounded-0">
                            </div>
                            <div class="text"> <a href="{% url 'auth_app:login' %}">Already have an account? Login</a> </div>
                        </form>
                        <div class="orting-badge">
                            Or
                        </div>
                        <div>
                            <a class="another-option" href="https://www.google.com/">
                                <img src="{% static 'assets/img/google.png' %}" alt="google">
                                Continue With Google
                            </a>
                        </div>
                        <div>
                            <a class="another-option another-option-two" href="https://www.facebook.com/">
                                <img src="{% static 'assets/img/facebook.png' %}" alt="google">
                                Continue With Facebook
                            </a>
                        </div>
                    </div>

                    <div class="banner">
                        <button type="button" class="rounded-0 login-btn" data-bs-toggle="modal"
                            data-bs-target="#loginModal">Log in</button>
                        <button type="button" class="theme-btn rounded-0 register-btn" data-bs-toggle="modal"
                            data-bs-target="#registrationModal">Create
                            Account</button>
                        <div class="signUpBg">
                            <img src="assets/img/registrationbg.jpg" alt="signUpBg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>