cart/urls.py
from django.urls import path
from .views import (
    add_to_cart_view, 
    get_cart_view, 
    cart, 
    delete_cart_item_view, 
    checkout,
    )

app_name = 'cart'
urlpatterns = [
    path('cart/', cart, name='cart'),
    path('add_to_cart/', add_to_cart_view, name='add_to_cart'),
    path('get_cart/', get_cart_view, name='get_cart'),
    path('remove_cart/<int:product_id>/', delete_cart_item_view, name='delete_cart_item'),
    path('checkout/', checkout, name='checkout'),
]

payment/urls.py
from django.urls import path
from .views import (
    payment_view
    )

app_name = 'payment'
urlpatterns = [
    path("payment/<str:order_reference>/<str:payment_method>/", payment_view, name="payment_view"),

]

cart/views.py
import requests
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.contrib import messages
import json
from django.views.decorators.http import require_GET
from auth_app.utils import session_access_required
from .utils import (
    get_cart_data, 
    cart_required,
    create_order,
    submit_billing_address, 
    )

# Create your views here.
def add_to_cart_view(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            product_id = data.get('product_id')
            quantity = int(data.get('quantity', 1))
        except (json.JSONDecodeError, ValueError):
            return JsonResponse({'error': 'Invalid input'}, status=400)

        # Build proxy handler URL
        proxy_url = request.build_absolute_uri(
            reverse('proxy_handler') + '?endpoint=/api/cart/add_to_cart/&endpoint_type=private'
        )

        # Prepare the payload
        payload = {
            'product_id': product_id,
            'quantity': quantity
        }

        access_token = request.session.get('access_token')
        sessionid = request.COOKIES.get('sessionid')

        # If no access token, treat user as guest and save to session
        if not access_token:
            cart = request.session.get('cart', [])
            for item in cart:
                if item['product_id'] == product_id:
                    item['quantity'] += quantity
                    break
            else:
                cart.append({'product_id': product_id, 'quantity': quantity})
            request.session['cart'] = cart
            # request.session['cart_changed'] = True
            return JsonResponse({'success': True, 'offline': True})
        
        try:

            response = requests.post(
                proxy_url,
                json=payload,
                headers={
                    # 'Authorization': f"Bearer {access_token}",
                    'Cookie': f'sessionid={sessionid}'
                }
            )

            if response.status_code == 200:
                # request.session['cart_changed'] = True
                return JsonResponse({'success': True})
            else:
                return JsonResponse({'success': False, 'error': 'Failed to add to cart'}, status=400)

        except requests.exceptions.RequestException:
            return JsonResponse({'error': 'Network error'}, status=500)
        
    return JsonResponse({'error': 'Invalid request method'}, status=405)

@require_GET
def get_cart_view(request):
    data = get_cart_data(request)
    return JsonResponse(data)

@cart_required
def cart(request):
    context = {

    }
    return render(request, 'cart.html', context)

def delete_cart_item_view(request, product_id):
    if request.method != 'DELETE' and request.method != 'POST':
        return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=405)

    access_token = request.session.get("access_token")

    if access_token:
        # Authenticated user - use proxy to call private API
        endpoint = f"/api/cart/delete_cart_item/{product_id}/"
        proxy_url = request.build_absolute_uri(
            reverse('proxy_handler') + f"?endpoint={endpoint}&endpoint_type=private"
        )

        sessionid = request.COOKIES.get('sessionid')
        try:
            response = requests.delete(
                proxy_url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    'Cookie': f'sessionid={sessionid}',
                }
            )
            if response.status_code == 200:
                return JsonResponse({'success': True})
            else:
                return JsonResponse({
                    'success': False,
                    'error': f"Failed with status {response.status_code}"
                }, status=response.status_code)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)

    else:
        # Guest user - modify session cart
        session_cart = request.session.get("cart", [])
        updated_cart = [item for item in session_cart if item.get("product_id") != product_id]
        request.session["cart"] = updated_cart
        return JsonResponse({'success': True})
    
@cart_required
@session_access_required
def checkout(request):
    if request.method == "POST":
        data = request.POST  # HTML form submission

        # --- Billing Data ---
        billing_data = {
            "address": data.get("billing_address"),
            "apartment": data.get("billing_apartment"),
            "nearest_bus_stop": data.get("billing_nearest_bus_stop"),
            "state": data.get("billing_state"),
            "country": data.get("billing_country"),
            "zip_code": data.get("billing_zip"),
        }

        billing_result = submit_billing_address(request, billing_data)
        if not billing_result.get("success"):
            messages.error(request, "Billing validation failed. Please check your details.")
            return render(request, "checkout.html", {
                "form_data": data,  # prefill old inputs
            })

        # --- Shipping Data ---
        use_different_shipping = data.get("different_address") == "on"

        if use_different_shipping:
            shipping_data = {
                "shipping_address": data.get("shipping_address"),
                "shipping_apartment": data.get("shipping_apartment"),
                "shipping_nearest_bus_stop": data.get("shipping_nearest_bus_stop"),
                "shipping_state": data.get("shipping_state"),
                "shipping_country": data.get("shipping_country"),
                "shipping_zip": data.get("shipping_zip"),
            }
        else:
            shipping_data = {
                "shipping_address": billing_data["address"],
                "shipping_apartment": billing_data["apartment"],
                "shipping_nearest_bus_stop": billing_data["nearest_bus_stop"],
                "shipping_state": billing_data["state"],
                "shipping_country": billing_data["country"],
                "shipping_zip": billing_data["zip_code"],
            }

        # --- Order Note ---
        order_note = {"note": data.get("order_note", "")}

        # --- Cart Items ---
        cart_data = get_cart_data(request)
        cart_items = cart_data.get("cart_items", [])

        order_result = create_order(request, shipping_data, order_note, cart_items)
        if not order_result.get("success"):
            messages.error(request, "Could not create order. Please try again.")
            return render(request, "checkout.html", {
                "form_data": data,
            })

        # --- Success: Redirect to payment ---
        order_reference = order_result.get("order_reference")
        print(f"Order Reference: {order_reference}")
        payment_method = data.get("payment_type")

        # messages.success(request, "Order created successfully! Please proceed to payment.")
        return redirect(
            "payment:payment_view",
            order_reference=order_reference,
            payment_method=payment_method
        )

    return render(request, "checkout.html", {})

payment/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseNotFound
from auth_app.utils import session_access_required
from django.conf import settings
from .utils import get_payment_verification, get_order_details
import requests

# Create your views here.
@session_access_required
def payment_view(request, order_reference, payment_method):
    # Grab the payment reference or transaction_id from query params
    ref_or_tx = request.GET.get("reference") or request.GET.get("transaction_id")

    # Get order details
    order = get_order_details(request, order_reference)
    # print(order)
    if not order or "id" not in order:
        return HttpResponseNotFound("Order not found")

    if order.get("payment_made"):
        return redirect("store:shop")

    order_id = order["id"]

    verification_result = None
    if ref_or_tx:  # Only verify if frontend callback included a reference/transaction_id
        verification_result = get_payment_verification(
            request, order_id, payment_method, reference=ref_or_tx
        )

        # Redirect if verification was successful
        if verification_result and verification_result.get("success"):
            return redirect("store:shop")

    context = {
        "order": order,
        "order_id": order_id,
        "order_reference": order_reference,
        "payment_method": payment_method,
        "reference": ref_or_tx,
        "verification_result": verification_result,
        "PAYSTACK_PUBLIC_KEY": settings.PAYSTACK_PUBLIC_KEY,
        "FLUTTERWAVE_PUBLIC_KEY": settings.FLUTTERWAVE_PUBLIC_KEY,
        "INTERSWITCH_MERCHANT_CODE": settings.INTERSWITCH_MERCHANT_CODE,
        "INTERSWITCH_PAY_ITEM_ID": settings.INTERSWITCH_PAY_ITEM_ID,
    }

    return render(request, "payment.html", context)

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} About">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - About
{% endblock title %}

{% block content %}
{% include "includes/about.html" %}
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!--<< Header Area >>-->

<head>
    <!-- ========== Meta Tags ========== -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="gramentheme">
    <meta name="keywords" content="{% for cat in categories %}{{ cat.name }}{% if not forloop.last %}, {% endif %}{% endfor %}">
    {% block meta %}
    
    {% endblock meta %}
    <!-- ======== Page title ============ -->
    <title>
        {% block title %}
    
        {% endblock title %}
    </title>
    <!--<< Favcion >>-->
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <!--<< Bootstrap min.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <!--<< All Min Css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
    <!--<< Animate.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <!--<< Magnific Popup.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <!--<< MeanMenu.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.css' %}">
    <!--<< Swiper Bundle.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/swiper-bundle.min.css' %}">
    <!--<< Nice Select.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <!--<< Icomoon.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/icomoon.css' %}">
    <!--<< Main.css >>-->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    

</head>

<body>

    <!-- Cursor follower -->
    <div class="cursor-follower"></div>

    <!-- Preloader Start -->
    <div id="preloader" class="preloader">
        <div class="animation-preloader">
            <div class="spinner">
            </div>
            <div class="txt-loading">
                <span data-text-preloader="B" class="letters-loading">
                    B
                </span>
                <span data-text-preloader="O" class="letters-loading">
                    O
                </span>
                <span data-text-preloader="O" class="letters-loading">
                    O
                </span>
                <span data-text-preloader="K" class="letters-loading">
                    K
                </span>
                <span data-text-preloader="H" class="letters-loading">
                    H
                </span>
                <span data-text-preloader="I" class="letters-loading">
                    I
                </span>
                <span data-text-preloader="V" class="letters-loading">
                    V
                </span>
                <span data-text-preloader="E" class="letters-loading">
                    E
                </span>
            </div>
            <p class="text-center">Loading</p>
        </div>
        <div class="loader">
            <div class="row">
                <div class="col-3 loader-section section-left">
                    <div class="bg"></div>
                </div>
                <div class="col-3 loader-section section-left">
                    <div class="bg"></div>
                </div>
                <div class="col-3 loader-section section-right">
                    <div class="bg"></div>
                </div>
                <div class="col-3 loader-section section-right">
                    <div class="bg"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Back To Top Start -->
    <button id="back-top" class="back-to-top">
        <i class="fa-solid fa-chevron-up"></i>
    </button>

    <!-- Offcanvas Area Start -->
    {% include "includes/offcanvas.html" %} 

    <!-- Sticky Header Section start  -->
    {% include "includes/header.html" %}

     <!-- Login Modal -->
    {% include "modals/login.html" %}
    
    <!-- Registration Modal -->
    {% include "modals/register.html" %}

    {% block content %}
        
    {% endblock content %}

    <!-- Footer Section Start -->
    {% include "includes/footer.html" %}

    <!--<< All JS Plugins >>-->
    <script src="{% static 'assets/js/jquery-3.7.1.min.js' %}"></script>
    <!--<< Viewport Js >>-->
    <script src="{% static 'assets/js/viewport.jquery.js' %}"></script>
    <!--<< Bootstrap Js >>-->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!--<< Nice Select Js >>-->
    <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
    <!--<< Waypoints Js >>-->
    <script src="{% static 'assets/js/jquery.waypoints.js' %}"></script>
    <!--<< Counterup Js >>-->
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <!--<< Swiper Slider Js >>-->
    <script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
    <!--<< MeanMenu Js >>-->
    <script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
    <!--<< Magnific Popup Js >>-->
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!--<< Wow Animation Js >>-->
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <!-- Gsap -->
    <script src="{% static 'assets/js/gsap.min.js' %}"></script>
    <!--<< Main.js >>-->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% block extra_js %}
    {% endblock extra_js %}

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% for message in messages %}
        {% if message.tags == 'success' %}
            
            <script>
                swal.fire({
                    "title": "Thank you!",
                    "text": "{{ message }}",
                    "icon": "success"
                })
            </script>
        {% else %}
            <script>
                swal.fire({
                    "title": "Sorry!",
                    "text": "{{ message }}",
                    "icon": "warning"
                })
            </script>
        {% endif %}
    {% endfor %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

    <script>
        const csrftoken = '{{ csrf_token }}';
        const addToCartUrl = "{% url 'cart:add_to_cart' %}";
        const getCartUrl = "{% url 'cart:get_cart' %}"; 
    </script>

    <script src="{% static 'assets/js/get_cart_details.js' %}"></script>
    <script src="{% static 'assets/js/add_to_cart.js' %}"></script>  
    <script src="{% static 'assets/js/delete_from_cart.js' %}"></script>  
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/68a3f7dd8039e2192972dd27/1j3080eir';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
    <!--End of Tawk.to Script-->

      
</body>

</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Cart">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Cart
{% endblock title %}

{% block content %}
{% include "includes/cart.html" %}
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Checkout">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Checkout
{% endblock title %}

{% block content %}
{% include "includes/checkout.html" %}
{% endblock content %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Contact">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Contact
{% endblock title %}

{% block content %}
{% include "includes/contact.html" %}
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Home">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Home
{% endblock title %}
{% block content %}
<!-- Hero Section start  -->
{% include "includes/hero.html" %}
<!-- Book Banner Section start  -->
{% include "includes/banner.html" %}

<!-- Shop Section Start -->
{% include "includes/product_slidder.html" %}

<!-- Featured Books Section Start -->
{% include "includes/featured_books.html" %}


<!-- Best Seller Section Start -->
{% comment %} {% include "includes/best_sellers.html" %} {% endcomment %}

<!-- Feature Section Start -->
{% include "includes/features.html" %}

<!-- Shop Section Start -->
{% comment %} {% include "includes/favorite_authors.html" %} {% endcomment %}

<!-- Cta Banner Section Start -->
{% include "includes/cta_banner.html" %}

<!-- Shop Section Start -->
{% comment %} {% include "includes/favorite_books.html" %} {% endcomment %}

<!-- Team Section Start -->
{% comment %} {% include "includes/authors.html" %} {% endcomment %}

<!-- News Section Start -->
{% comment %} {% include "includes/latest_news.html" %}  {% endcomment %}
{% endblock content %}

{% block extra_js %}
<script>
document.addEventListener("DOMContentLoaded", function () {
    const cartCount = {{ cart_count|default:0 }};
    const offcanvas = document.querySelector(".offcanvas__info");
    const overlay = document.querySelector(".offcanvas__overlay");
    const closeBtn = document.querySelector(".offcanvas-close-btn");

    if (cartCount > 0) {
        // Show the offcanvas & overlay
        offcanvas.classList.add("info-open");
        overlay.classList.add("overlay-open");
    }

    // Close button handler
    closeBtn.addEventListener("click", function () {
        offcanvas.classList.remove("info-open");
        overlay.classList.remove("overlay-open");
    });

    // Overlay click also closes offcanvas
    overlay.addEventListener("click", function () {
        offcanvas.classList.remove("info-open");
        overlay.classList.remove("overlay-open");
    });
});
</script>
{% endblock extra_js %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Login">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Login
{% endblock title %}

{% block content %}
{% endblock content %}

{% block extra_js %}
<script>
document.addEventListener("DOMContentLoaded", function() {
    // Remove close button
    {% comment %} const closeBtn = document.querySelector('#loginModal .close-btn');
    if (closeBtn) {
        closeBtn.remove();
    } {% endcomment %}

    // Force modal open and prevent closing
    var myModal = new bootstrap.Modal(document.getElementById('loginModal'), {
        backdrop: 'static', // clicking outside won't close it
        keyboard: false     // pressing Esc won't close it
    });
    myModal.show();
});
</script>
{% endblock extra_js %}

templates/payment.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Payment">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Payment
{% endblock title %}

{% block content %}
{% endblock content %}

{% block extra_js %}
{% if payment_method == 'paystack' %}
<script src="https://js.paystack.co/v2/inline.js"></script>
<script type="text/javascript">
    
    function payWithPaystack() {
        var handler = PaystackPop.setup({
            key: '{{ PAYSTACK_PUBLIC_KEY }}',
            email: '{{ user_profile.email }}',
            amount: {{ order.total_price|floatformat:0 }} * 100,
            currency: "NGN",
            ref: '' + Math.floor((Math.random() * 1000000000) + 1),
            callback: function(response) {
                window.location.href = "{% url 'payment:payment_view' order_reference payment_method %}?reference=" + response.reference;
            },
            onClose: function() {
                alert('Payment was not completed.');
            }
        });
        handler.openIframe();
    }

    window.onload = function () {
        payWithPaystack();
    };
</script>
{% endif %}

{% if payment_method == 'flutterwave' %}
<script src="https://checkout.flutterwave.com/v3.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    FlutterwaveCheckout({
      public_key: "{{ FLUTTERWAVE_PUBLIC_KEY }}",
      tx_ref: "{{ order_reference }}",
      amount: {{order.total_price}},
      currency: "NGN",
      payment_options: "card, ussd, banktransfer",
      redirect_url: "{% url 'payment:payment_view' order_reference payment_method %}",
      customer: {
        email: "{{ user_profile.email }}",
        name: "{{ user_profile.first_name }} {{ user_profile.last_name }}"
      },
      customizations: {
        title: "{{business_name}}",
        description: "Payment for order {{ order_reference }}"
      }
    });
  });
</script>
{% endif %}

{% if payment_method == 'interswitch' %}
<script src="https://newwebpay.qa.interswitchng.com/inline-checkout.js"></script>
<script>
(function() {
    const redirectUrl = "{% url 'payment:payment_view' order_reference payment_method %}?reference={{ order_reference }}";
    const paymentAmount = {{ order.total_price|floatformat:0 }} * 100;

    function paymentCallback(response) {
        console.log("Interswitch Payment Response:", response);

        if (response?.resp === '00') {
            // Successful payment
            window.location.href = redirectUrl;
        } else {
            alert("Payment was not successful. Please try again.");
        }
    }

    const paymentRequest = {
        merchant_code: "{{ INTERSWITCH_MERCHANT_CODE }}",
        pay_item_id: "{{ INTERSWITCH_PAY_ITEM_ID }}",
        txn_ref: "{{ order_reference }}",
        site_redirect_url: redirectUrl,
        amount: paymentAmount,
        currency: 566,
        cust_email: "{{ user_profile.email }}",
        cust_name: "{{ user_profile.first_name }} {{ user_profile.last_name }}",
        onComplete: paymentCallback,
        mode: "TEST"
    };

    window.webpayCheckout(paymentRequest);
})();
</script>
{% endif %}
{% endblock extra_js %}

templates/product_details.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{product.title}}">
<meta property="og:description" content="{{product.description}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{{ product.images.0.image }}">
{% endblock meta %}
{% block title %}
{{business_name}} - {{product.title}}
{% endblock title %}

{% block content %}
{% include "includes/product_details.html" %}
{% endblock content %}

{% comment %} {% block extra_js %}
<script>
document.querySelector('#contact-form').addEventListener('submit', function(e) {
    e.preventDefault();

    const score = document.querySelector('input[name="score"]:checked')?.value;
    const review = document.querySelector('textarea[name="review"]').value;

    fetch('{{ rating_url }}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({ score: score, review: review })
    })
    .then(res => res.json())
    .then(data => {
        console.log(data);
        alert('Review submitted!');
    })
    .catch(err => console.error(err));
});
</script>
{% endblock extra_js %} {% endcomment %}

templates/register.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Register">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Register
{% endblock title %}

{% block content %}
{% endblock content %}

{% block extra_js %}
<script>
document.addEventListener("DOMContentLoaded", function() {
    // Remove close button
    {% comment %} const closeBtn = document.querySelector('#registrationModal .close-btn');
    if (closeBtn) {
        closeBtn.remove();
    } {% endcomment %}

    var myModal = new bootstrap.Modal(document.getElementById('registrationModal'), {
        backdrop: 'static', // clicking outside won't close it
        keyboard: false     // pressing Esc won't close it
    });
    myModal.show();
});
</script>
{% endblock extra_js %}

templates/shop.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Shop">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Shop
{% endblock title %}

{% block content %}
{% include "includes/shop.html" %}
{% endblock content %}

{% block extra_js %}
<script>
document.addEventListener("DOMContentLoaded", function () {
    const cartCount = {{ cart_count|default:0 }};
    const offcanvas = document.querySelector(".offcanvas__info");
    const overlay = document.querySelector(".offcanvas__overlay");
    const closeBtn = document.querySelector(".offcanvas-close-btn");

    if (cartCount > 0) {
        // Show the offcanvas & overlay
        offcanvas.classList.add("info-open");
        overlay.classList.add("overlay-open");
    }

    // Close button handler
    closeBtn.addEventListener("click", function () {
        offcanvas.classList.remove("info-open");
        overlay.classList.remove("overlay-open");
    });

    // Overlay click also closes offcanvas
    overlay.addEventListener("click", function () {
        offcanvas.classList.remove("info-open");
        overlay.classList.remove("overlay-open");
    });
});
</script>
{% endblock extra_js %}

templates/wish.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<meta property="og:title" content="{{business_name}} Wish List">
<meta property="og:description" content="Welcome to {{business_name}}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:image" content="{% static 'assets/img/logo/black-logo.svg' %}">
{% endblock meta %}
{% block title %}
{{business_name}} - Wish List
{% endblock title %}

{% block content %}
{% include "includes/wishlist.html" %}
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}